##### Sign In
POST http://localhost:4000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "avcc@gmail.com",
    "password": "123"
}
##### Sign Up
POST http://localhost:4000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "avcc2@gmail.com",
    "password": "123"
}

##### Log out
POST http://localhost:4000/api/auth/logout HTTP/1.1
content-type: application/json

##### List User
GET http://localhost:4000/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhdmNjQGdtYWlsLmNvbSIsImlhdCI6MTY0OTc3Njc2MX0.2oAMvQTZRGY4DHKEOaw6NKNLdcZ36tsGCVivYWFfxtw

##### Detail User
GET http://localhost:4000/api/user/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhdmNjQGdtYWlsLmNvbSIsImlhdCI6MTY0OTc3Njc2MX0.2oAMvQTZRGY4DHKEOaw6NKNLdcZ36tsGCVivYWFfxtw

